name: Manual workflow

on:
  workflow_dispatch:


jobs:
  test:
    strategy:
      matrix:
        os: [ macos-14, macos-14-large, macos-15-xlarge ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Xcodes
        run: |
           xcrun simctl list devices
