name: Manual workflow

on:
  workflow_dispatch:


jobs:
  test:
    strategy:
      matrix:
        os: [ macos-14-large ]
        attempt: [ 1, 2, 3, 4, 5 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16_beta_6'
      - run: |
            xcodebuild -downloadPlatform visionOS
