name: Manual workflow

on:
  workflow_dispatch:


jobs:
  test:
    strategy:
      matrix:
        os: [ macos-14 ]
        xcode: [ 16, 16.1 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Disk space
        run: |
          diskutil info / | grep "Free Space"
          df -h
#      - uses: actions/checkout@v4
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '${{ matrix.xcode }}-beta'
      - name: Download visionOS
        run: |
            xcode-select -p
            xcodebuild -version
            xcodebuild -runFirstLaunch 
            xcodebuild -downloadAllPlatforms
