name: Manual workflow

on:
  workflow_dispatch:


jobs:
  test:
    strategy:
      matrix:
        os: [ macos-14 ]
        attempt: [ 1, 2, 3, 4, 5 ]
        xcode: [ 16.0, 16.1 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '${{ matrix.xcode }}-beta'
      - name: RM Xcode platforms
        run: |
            sudo rm -rf /Library/Developer/CoreSimulator/Profiles/Runtimes/*
            sudo rm -rf ~/Library/Developer/Xcode/DerivedData/*
            defaults delete com.apple.dt.Xcode
      - name: Download visionOS
        run: |
            xcodebuild -downloadPlatform visionOS
