name: Manual workflow

on:
  workflow_dispatch:


jobs:
  test:
    strategy:
      matrix:
        os: [ macos-14, macos-14-large ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Xcodes
        run: |
           echo "---Links---"
           find /Applications -name "Xcode_*" -maxdepth 1 -mindepth 1 -type l
           echo "---Folders---"
           find /Applications -name "Xcode_*" -maxdepth 1 -mindepth 1 -type d
