name: Manual workflow

on:
  workflow_dispatch:


jobs:
  test:
    strategy:
      matrix:
        os: [ macos-15-xlarge ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Env
        run: |
            cat ~/.bashrc || true
