name: Manual workflow

on:
  workflow_dispatch:


jobs:
  test:
    strategy:
      matrix:
        attempt: [ 1, 2, 3, 4, 5 ]
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
      - uses: actions/setup-node@v4
        with:
          node-version: 18
