name: Manual workflow

on:
  workflow_dispatch:


jobs:
  test:
    strategy:
      matrix:
        os: [ macos-14 ]
        xcode: [ 15.4 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Disk space
        run: |
          find /Applications -name "Xcode*" -maxdepth 1 -mindepth 1 ! -type l
          diskutil info / | grep "Free Space"
          df -h
#      - uses: actions/checkout@v4
      - name: Download visionOS
        run: |
            xcode-select -p
            sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
            xcodebuild -version
            xcodebuild -showsdks
            sudo xcodebuild -runFirstLaunch 
            sudo xcodebuild -downloadPlatform visionOS
            sudo xcodebuild -runFirstLaunch 
      - name: Disk space
        run: |
          diskutil info / | grep "Free Space"
          df -h
