
name: Pwsh execution log

on:
  workflow_dispatch:

    
jobs:
  build:
    strategy:
      matrix: 
        os: [ "windows-2019", "windows-2022" ]
        retry: [ "1", "2", "3", "4" ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install WPT and run log collection
        run: |
          choco install windows-performance-toolkit
          "C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\xperf.exe" -start -on LOADER+PROC_THREAD+DISK_IO+HARD_FAULTS+DPC+INTERRUPT+CSWITCH+PERF_COUNTER+FILE_IO_INIT+REGISTRY
        shell: cmd

      - name: First pwsh invocation
        run: git --help
        shell: pwsh

      - name: End of a log collection
        run: |
          "c:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\xperf.exe" -d tmp1.etl
        shell: cmd

      - name: Archive ETL
        uses: actions/upload-artifact@v3
        with:
          name: WPP-${{ matrix.os }}-${{ matrix.retry }}-1
          path: tmp1.etl
  
      - name: Run log collection
        run: |
          "C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\xperf.exe" -start -on LOADER+PROC_THREAD+DISK_IO+HARD_FAULTS+DPC+INTERRUPT+CSWITCH+PERF_COUNTER+FILE_IO_INIT+REGISTRY
        shell: cmd

      - name: Second pwsh invocation
        run: git --help
        shell: pwsh

      - name: End of a log collection
        run: |
          "c:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\xperf.exe" -d tmp2.etl
        shell: cmd

      - name: Archive ETL
        uses: actions/upload-artifact@v3
        with:
          name: WPP-${{ matrix.os }}-${{ matrix.retry }}-2
          path: tmp2.etl
