name: SBOM

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ windows-2019, windows-2022 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install SYFT tool on Windows
        if: ${{ runner.os == 'Windows' }}
        run: curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b D:/syft
      - name: Install SYFT tool on Ubuntu or macOS
        if: ${{ runner.os != 'Windows' }}
        run: curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
      - name: Run SYFT on Windows
        if: ${{ runner.os == 'Windows' }}
        run: D:/syft/syft dir:C:/ -vv -o spdx-json=sbom.json
      - name: Run SYFT on Ubuntu
        if: ${{ runner.os == 'Linux' }}
        run: syft dir:/ -vv -o spdx-json=sbom.json
      - name: Run SYFT on macOS
        if: ${{ runner.os == 'macOS' }}
        run: sudo syft dir:/ -vv -o spdx-json=sbom.json --exclude ./Users --exclude ./System/Volumes --exclude ./private
        shell: bash
      - name: Compress SBOM file
        run: Compress-Archive sbom.json sbom.json.zip
        shell: pwsh
      #Upload artifact action
      - uses: actions/upload-artifact@v3
        with:
          name: sbom-${{ matrix.os }}
          path: sbom.json.zip
          if-no-files-found: warn
